import { fileRole } from "@churchapps/helpers";

// The package layout of a live song (vision/files.md section 0, WorshipCommonsContent/README.md "Layout"):
//   songs/<lang>/<license-section>/<slug>-<id>/{sources,masters,derivatives}/<file>
// The bucket holds exactly the content repo's layout under the commons prefix, so a song's storage key is its
// repo path. assetFiles.name stores that prefix-relative key ("songs/en/public-domain/amazing-grace-YxPfAFYWOaG/
// sources/tune.mid", or "works/amazing-grace/sources/tune.abc" for a file inherited from the work). Rows seeded
// before the cut-over hold a package-relative name ("sources/tune.mid") and keep resolving to the old id-keyed
// folder — see ContentLibraryHelper.liveKey. Roles are always decided by the basename, so the folder never
// changes what a file is. Assets that are not songs keep their flat layout. Pure: no storage, no repos.
//
// LANG_CODES, LICENSE_SECTIONS and slugify are copies of WorshipCommonsContent/tools/lib.mjs and
// licenses/licenses.json; the two must agree or validate.mjs rejects what the API publishes.

export const PACKAGE_DIRS = ["sources", "masters", "derivatives"] as const;
const IN_PACKAGE_DIR = /^(sources|masters|derivatives)\//;
const PACKAGE_KEY = /^(songs|works|writers)\//;
const PACKAGE_TAIL = /\/(sources|masters|derivatives)\/[^/]+$/;
/** Package derivatives the shared registry does not name (generated by the content pipeline, never uploaded). */
export const PACKAGE_ROLES: Record<string, string> = { "score.musicxml": "score", "slides.json": "slides", "chart.chordpro": "chart", "chart.pdf": "chartPdf", "attribution.txt": "attribution", "cover-thumb.webp": "thumb", "duration.json": "duration" };
const MASTER_FILES = new Set(["song.json", "lyrics.chordpro", "cover.webp"]);
// timing.json is uploadable but lives with the derivatives (files.md: "the one exception"); score.musicxml is
// deliberately absent — an uploaded score is a source until a reviewer proofreads it into masters/
const DERIVATIVE_FILES = new Set([
  "slides.json", "chart.chordpro", "chart.pdf", "attribution.txt", "cover-thumb.webp", "duration.json", "timing.json", "sources.txt"
]);
// the browser-made thumbnail takes the pipeline's name so a fresh upload replaces the generated one in place
const RENAMED: Record<string, string> = { "art-thumb.webp": "derivatives/cover-thumb.webp" };

export const LANG_CODES: Record<string, string> = {
  English: "en",
  German: "de",
  Spanish: "es",
  Latin: "la",
  French: "fr",
  Portuguese: "pt",
  Russian: "ru",
  Malayalam: "ml",
  Albanian: "sq",
  Hungarian: "hu",
  Zulu: "zu",
  Swedish: "sv"
};

/** song.json "license" id → the songs/<lang>/<section>/ folder (licenses/licenses.json). */
export const LICENSE_SECTIONS: Record<string, string> = {
  PD: "public-domain",
  WC: "wc-license",
  "CC-BY": "cc-by",
  "CC-BY-SA": "cc-by-sa",
  "CC-BY-NC": "cc-by-nc",
  "CC-BY-NC-SA": "cc-by-nc-sa"
};

/** Folder name from a title: NFC lowercase, apostrophes dropped, other punctuation/space runs → "-". Cosmetic only. */
export function slugify(title: string | null | undefined): string {
  return (title || "").normalize("NFC").toLowerCase()
    .replace(/['’ʼ]/gu, "")
    .replace(/[^\p{L}\p{M}\p{N}]+/gu, "-")
    .replace(/^-+|-+$/g, "") || "untitled";
}

/** `<slug>-<id>`: the id is the identity and can begin with "-" or "_", so it is always the last 11 characters. */
export function packageFolder(title: string | null | undefined, id: string): string {
  return `${slugify(title)}-${id}`;
}

export function idFromFolder(folder: string): string | null {
  return folder.length > 12 && folder[folder.length - 12] === "-" ? folder.slice(-11) : null;
}

export function langCode(language: string | null | undefined): string {
  return LANG_CODES[language || ""] ?? (language ? slugify(language) : "und");
}

export function licenseSection(license: string | null | undefined): string {
  return LICENSE_SECTIONS[license || ""] ?? (license ? slugify(license) : "unlicensed");
}

/** The package dir a song gets when it first lands in the layout: songs/<lang>/<section>/<slug>-<id>. Frozen from then on. */
export function songPackageDir(asset: { id?: string; name?: string; language?: string; license?: string }): string {
  return `songs/${langCode(asset.language)}/${licenseSection(asset.license)}/${packageFolder(asset.name, asset.id || "")}`;
}

/** True when `name` is a prefix-relative catalog key (songs/…, works/…, writers/…) rather than a folder-relative name. */
export function isPackageKey(name: string | null | undefined): boolean {
  return PACKAGE_KEY.test(name || "");
}

/** The song package a key belongs to ("songs/en/public-domain/amazing-grace-YxPfAFYWOaG"); null for works, writers and legacy names. */
export function packageDirOf(name: string | null | undefined): string | null {
  const n = name || "";
  return n.startsWith("songs/") && PACKAGE_TAIL.test(n) ? n.replace(PACKAGE_TAIL, "") : null;
}

/** The song's frozen package dir, read from any live file already in it; null when none is (a legacy or brand-new song). */
export function packageDirFrom(files: { name?: string }[]): string | null {
  for (const f of files) {
    const dir = packageDirOf(f.name);
    if (dir) return dir;
  }
  return null;
}

/** Folder-relative form of any name: "songs/…/sources/tune.mid" → "sources/tune.mid"; legacy and flat names unchanged. */
export function relativeName(name: string | null | undefined): string {
  const n = name || "";
  const m = n.match(/\/(sources|masters|derivatives)\/([^/]+)$/);
  return isPackageKey(n) && m ? `${m[1]}/${m[2]}` : n;
}

export function baseName(name: string | null | undefined): string {
  return (name || "").split("/").pop() || "";
}

/** The role of a live or pending file, whatever folder it sits in. */
export function packageRole(name: string | null | undefined): string {
  const base = baseName(name);
  return PACKAGE_ROLES[base] ?? fileRole(base);
}

/** True when `name` already carries a package folder. */
export function inPackageDir(name: string | null | undefined): boolean {
  return IN_PACKAGE_DIR.test(name || "") || isPackageKey(name);
}

/**
 * Where a flat (pending or conventional) file name lands in a live song package, folder-relative. Names that
 * already carry a folder, manifest.json, and every non-song asset's files are returned unchanged.
 */
export function packagePath(assetType: string | undefined, name: string): string {
  if (assetType !== "song" || !name || inPackageDir(name) || name === "manifest.json") return name;
  if (RENAMED[name]) return RENAMED[name];
  if (MASTER_FILES.has(name) || /^art\.[^./]+$/.test(name)) return `masters/${name}`;
  if (DERIVATIVE_FILES.has(name)) return `derivatives/${name}`;
  return `sources/${name}`;
}

/** The full prefix-relative key a file gets inside `packageDir`; a name that is already a catalog key is kept. */
export function packageKey(packageDir: string | null, assetType: string | undefined, name: string): string {
  const placed = packagePath(assetType, name);
  if (!packageDir || assetType !== "song" || isPackageKey(placed)) return placed;
  return `${packageDir}/${placed}`;
}

/** The live file that a flat name refers to — same basename after placement, so a re-upload replaces in place. */
export function findByBase<T extends { name?: string }>(files: T[], assetType: string | undefined, name: string): T | undefined {
  const base = baseName(packagePath(assetType, name));
  return files.find((f) => baseName(f.name) === base);
}
