import { fileRole } from "@churchapps/helpers";

// The package layout of a live song folder (vision/files.md section 0): every file sits in exactly one of
// sources/ (came from somewhere else), masters/ (a person authored or approved it) or derivatives/ (a machine
// built it), with manifest.json — the inventory — at the package root. assetFiles.name stores the
// folder-relative name ("sources/tune.mid"); pending uploads stay flat and are placed on promotion by
// packagePath(). Roles are always decided by the basename, so the folder never changes what a file is.
// Assets that are not songs keep their flat layout. Pure: no storage, no repos.

export const PACKAGE_DIRS = ["sources", "masters", "derivatives"] as const;
const IN_PACKAGE_DIR = /^(sources|masters|derivatives)\//;
/** Package derivatives the shared registry does not name (generated by the content pipeline, never uploaded). */
export const PACKAGE_ROLES: Record<string, string> = { "score.musicxml": "score", "slides.json": "slides", "chart.chordpro": "chart", "chart.pdf": "chartPdf", "attribution.txt": "attribution", "cover-thumb.webp": "thumb", "duration.json": "duration" };
const MASTER_FILES = new Set(["song.json", "lyrics.chordpro", "cover.webp"]);
// timing.json is uploadable but lives with the derivatives (files.md: "the one exception"); score.musicxml is
// deliberately absent — an uploaded score is a source until a reviewer proofreads it into masters/
const DERIVATIVE_FILES = new Set([
  "slides.json", "chart.chordpro", "chart.pdf", "attribution.txt", "cover-thumb.webp", "duration.json", "timing.json", "sources.txt"
]);
// the browser-made thumbnail takes the pipeline's name so a fresh upload replaces the generated one in place
const RENAMED: Record<string, string> = { "art-thumb.webp": "derivatives/cover-thumb.webp" };

export function baseName(name: string | null | undefined): string {
  return (name || "").split("/").pop() || "";
}

/** The role of a live or pending file, whatever folder it sits in. */
export function packageRole(name: string | null | undefined): string {
  const base = baseName(name);
  return PACKAGE_ROLES[base] ?? fileRole(base);
}

/** True when `name` already carries a package folder. */
export function inPackageDir(name: string | null | undefined): boolean {
  return IN_PACKAGE_DIR.test(name || "");
}

/**
 * Where a flat (pending or conventional) file name lands in a live song package. Names that already carry
 * a folder, manifest.json, and every non-song asset's files are returned unchanged.
 */
export function packagePath(assetType: string | undefined, name: string): string {
  if (assetType !== "song" || !name || inPackageDir(name) || name === "manifest.json") return name;
  if (RENAMED[name]) return RENAMED[name];
  if (MASTER_FILES.has(name) || /^art\.[^./]+$/.test(name)) return `masters/${name}`;
  if (DERIVATIVE_FILES.has(name)) return `derivatives/${name}`;
  return `sources/${name}`;
}

/** The live file that a flat name refers to — same basename after placement, so a re-upload replaces in place. */
export function findByBase<T extends { name?: string }>(files: T[], assetType: string | undefined, name: string): T | undefined {
  const base = baseName(packagePath(assetType, name));
  return files.find((f) => baseName(f.name) === base);
}
