import { fileRole } from "@churchapps/helpers";

// The package layout of a live song (WorshipCommonsContent/tools/lib.mjs, README.md "What's in a song"):
//   songs/<lang>/<slug>-<id>/song.json, sources/<file>, output/composition/<file>, output/audio/<file>, output/*.zip
// Packages written before 2026-09 sit in songs/<lang>/<license-section>/<slug>-<id>/{sources,masters,derivatives}/
// and keep that placement (isLegacyDir) until the content repo moves them.
// The bucket holds exactly the content repo's layout under the commons prefix, so a song's storage key is its
// repo path. assetFiles.name stores that prefix-relative key ("songs/en/amazing-grace-YxPfAFYWOaG/
// sources/tune.mid"; a translation's inherited file is keyed under its parent song's package). Rows seeded
// before the cut-over hold a package-relative name ("sources/tune.mid") and keep resolving to the old id-keyed
// folder — see ContentLibraryHelper.liveKey. Roles are the basename except the pipeline stems pack: any zip
// in output/audio/ (not output/audio.zip, the listening pack). Title-and-BPM zip names are for Ableton, not
// the API contract. Assets that are not songs keep their flat layout. Pure: no storage, no repos.
//
// LANG_CODES and slugify are copies of WorshipCommonsContent/tools/lib.mjs; the two must agree or validate.mjs
// rejects what the API publishes.

export const PACKAGE_DIRS = ["sources", "output", "masters", "derivatives"] as const;
const IN_PACKAGE_DIR = /^(sources|output|masters|derivatives)\//;
const PACKAGE_KEY = /^(songs|works|writers)\//;
// songs/<lang>/[<section>/]<slug>-<id>, followed by song.json or one of the package folders; the id is the last 11 chars
const PACKAGE_DIR = /^(songs\/[^/]+\/(?:[^/]+\/)?[^/]*-[A-Za-z0-9_-]{11})\/(?:song\.json$|(?:sources|output|masters|derivatives)\/)/;
/** Package derivatives the shared registry does not name (generated by the content pipeline, never uploaded). */
export const PACKAGE_ROLES: Record<string, string> = { "score.musicxml": "score", "slides.json": "slides", "chart.chordpro": "chart", "chart.pdf": "chartPdf", "attribution.txt": "attribution", "cover-thumb.webp": "thumb", "duration.json": "duration", "composition.zip": "compositionZip", "audio.zip": "audioZip", "instrumental.m4a": "instrumental", "preview.m4a": "preview" };
const MASTER_FILES = new Set(["song.json", "lyrics.chordpro", "cover.webp"]);
// timing.json is uploadable but lives with the derivatives (files.md: "the one exception"); score.musicxml is
// deliberately absent — an uploaded score is a source until a reviewer proofreads it into masters/
const DERIVATIVE_FILES = new Set([
  "slides.json", "chart.chordpro", "chart.pdf", "attribution.txt", "cover-thumb.webp", "duration.json", "timing.json", "sources.txt"
]);
// Preferred-first when a varchar(100)-truncated basename is ambiguous (chart. → chordpro, not pdf).
const FILES_BY_FOLDER: Record<string, string[]> = {
  derivatives: [
    "chart.chordpro", "slides.json", "attribution.txt", "duration.json", "cover-thumb.webp", "sources.txt", "timing.json", "score.musicxml", "chart.pdf"
  ],
  masters: ["song.json", "cover.webp", "score.musicxml", "lyrics.chordpro"],
  sources: ["tune.mid", "tune.abc", "timing.json", "cover.webp", "sheetPdf.pdf", "score.musicxml"],
  output: ["composition.zip", "audio.zip"]
};
FILES_BY_FOLDER.composition = FILES_BY_FOLDER.derivatives;
const COMPLETE_EXT = /\.(mp3|wav|m4a|ogg|flac|zip|pdf|mid|midi|abc|webp|jpg|jpeg|png|json|txt|cho|chordpro|musicxml|xml|mxl)$/i;
// the browser-made thumbnail takes the pipeline's name so a fresh upload replaces the generated one in place
const RENAMED: Record<string, string> = { "art-thumb.webp": "cover-thumb.webp" };

export const LANG_CODES: Record<string, string> = {
  English: "en",
  German: "de",
  Spanish: "es",
  Latin: "la",
  French: "fr",
  Portuguese: "pt",
  Russian: "ru",
  Malayalam: "ml",
  Albanian: "sq",
  Hungarian: "hu",
  Zulu: "zu",
  Swedish: "sv",
  Dutch: "nl",
  Italian: "it",
  Chinese: "zh",
  Afrikaans: "af",
  Maltese: "mt",
  Romanian: "ro",
  Slovak: "sk",
  Finnish: "fi"
};

/** Folder name from a title: NFC lowercase, apostrophes dropped, other punctuation/space runs → "-". Cosmetic only. */
export function slugify(title: string | null | undefined): string {
  return (title || "").normalize("NFC").toLowerCase()
    .replace(/['’ʼ]/gu, "")
    .replace(/[^\p{L}\p{M}\p{N}]+/gu, "-")
    .replace(/^-+|-+$/g, "") || "untitled";
}

/** `<slug>-<id>`: the id is the identity and can begin with "-" or "_", so it is always the last 11 characters. */
export function packageFolder(title: string | null | undefined, id: string): string {
  return `${slugify(title)}-${id}`;
}

export function idFromFolder(folder: string): string | null {
  return folder.length > 12 && folder[folder.length - 12] === "-" ? folder.slice(-11) : null;
}

export function langCode(language: string | null | undefined): string {
  return LANG_CODES[language || ""] ?? (language ? slugify(language) : "und");
}

/** The package dir a song gets when it first lands in the layout: songs/<lang>/<slug>-<id>. Frozen from then on. */
export function songPackageDir(asset: { id?: string; name?: string; language?: string }): string {
  return `songs/${langCode(asset.language)}/${packageFolder(asset.name, asset.id || "")}`;
}

/** A pre-2026-09 package (songs/<lang>/<section>/<slug>-<id>) or no package at all: files keep the masters/derivatives placement. */
export function isLegacyDir(packageDir: string | null | undefined): boolean {
  return !packageDir || packageDir.split("/").length > 3;
}

/** True when `name` is a prefix-relative catalog key (songs/…, writers/…, or a legacy works/…) rather than a folder-relative name. */
export function isPackageKey(name: string | null | undefined): boolean {
  return PACKAGE_KEY.test(name || "");
}

/** The song package a key belongs to ("songs/en/amazing-grace-YxPfAFYWOaG"); null for writers and legacy names. */
export function packageDirOf(name: string | null | undefined): string | null {
  return completedPackageName(name).match(PACKAGE_DIR)?.[1] ?? null;
}

/**
 * The song's frozen package dir, read from any live file already in it; null when none is (a legacy or brand-new song).
 * With `id`, only the song's own package counts: a translation's inherited files sit in its parent's package.
 */
export function packageDirFrom(files: { name?: string }[], id?: string): string | null {
  for (const f of files) {
    const dir = packageDirOf(f.name);
    if (dir && (!id || idFromFolder(baseName(dir)) === id)) return dir;
  }
  return null;
}

/** Folder-relative form of any name: "songs/…/sources/master/a.wav" → "sources/master/a.wav"; legacy and flat names unchanged. */
export function relativeName(name: string | null | undefined): string {
  const n = name || "";
  const dir = packageDirOf(n);
  if (dir) return n.slice(dir.length + 1);
  const m = n.match(/\/(sources|masters|derivatives)\/([^/]+)$/); // works/<slug>/…
  return isPackageKey(n) && m ? `${m[1]}/${m[2]}` : n;
}

export function baseName(name: string | null | undefined): string {
  return (name || "").split("/").pop() || "";
}

/**
 * Restore a catalog key MySQL truncated at the old assetFiles.name varchar(100).
 * No-op when the basename is already a complete file (including extra/*.mp3 and output/audio titled zips).
 */
export function completedPackageName(name: string | null | undefined): string {
  const n = (name || "").replace(/\\/g, "/");
  if (!n) return n;
  const base = baseName(n);
  if (!base) return n;
  if (PACKAGE_ROLES[base] || MASTER_FILES.has(base) || DERIVATIVE_FILES.has(base) || COMPLETE_EXT.test(base)) return n;
  const i = n.lastIndexOf("/");
  if (i < 0) {
    const hit = Object.values(FILES_BY_FOLDER).flat().find((f) => f.startsWith(base));
    return hit || n;
  }
  const folder = n.slice(n.lastIndexOf("/", i - 1) + 1, i);
  const hit = (FILES_BY_FOLDER[folder] || []).find((f) => f.startsWith(base));
  return hit ? `${n.slice(0, i)}/${hit}` : n;
}

// what the content repo's generators write that a consumer reads (the seed registers the same set), plus the lyric
// timings its publish job aligns to the recording — kept in sources/ like every other song's timing.json
const OUTPUT_FILE = /^(output\/(composition\/(score\.musicxml|score\.mid|slides\.json|chart\.chordpro|chart\.pdf|attribution\.txt|duration\.json|cover-thumb\.webp|sources\.txt)|composition\.zip|audio\.zip|audio\/[^/]+\.(zip|m4a))|sources\/timing\.json)$/i;

/** The registrable catalog keys in a listing of a package's generated files (full storage keys or catalog keys). */
export function outputKeys(packageDir: string, listed: string[]): string[] {
  const prefix = `${packageDir}/`;
  return listed.map((k) => k.replace(/\\/g, "/").replace(/^commons\//, ""))
    .filter((n) => n.startsWith(prefix) && OUTPUT_FILE.test(n.slice(prefix.length)));
}

/** Catalog keys to register from an output/audio listing. `listed` may be full keys or basenames. */
export function audioKeysToAdd(packageDir: string, listed: string[], existing: string[]): string[] {
  const have = new Set(existing);
  const out: string[] = [];
  for (const key of listed) {
    const raw = key.replace(/\\/g, "/").replace(/^commons\//, "");
    const name = raw.includes("/") ? raw : `${packageDir}/output/audio/${raw}`;
    if (!/\/output\/audio\/[^/]+\.(zip|m4a)$/i.test(name) || have.has(name)) continue;
    have.add(name);
    out.push(name);
  }
  return out;
}

/** The role of a live or pending file, whatever folder it sits in. */
export function packageRole(name: string | null | undefined): string {
  const n = completedPackageName(name);
  const base = baseName(n);
  // song.json owns "song"; a harvested writer recording named song.mp3 is the demo, not the package record
  if (/^song\.(mp3|wav|m4a|ogg|flac)$/i.test(base)) return "demoAudio";
  // catalog.json already names this stemsZipUrl; the folder is the contract, not the title-BPM filename
  if (/\/output\/audio\/[^/]+\.zip$/i.test(n)) return "stemsZip";
  return PACKAGE_ROLES[base] ?? fileRole(base);
}

/** True when `name` already carries a package folder. */
export function inPackageDir(name: string | null | undefined): boolean {
  return IN_PACKAGE_DIR.test(name || "") || isPackageKey(name);
}

/**
 * Where a flat (pending or conventional) file name lands in a live song package, folder-relative. Names that
 * already carry a folder, manifest.json, and every non-song asset's files are returned unchanged. The pipeline
 * layout (lib.mjs): song.json at the root, what a tool cannot rebuild in sources/ (the master recording in
 * sources/master/, where tools/pack/build.py looks), what generate.mjs rebuilds in output/composition/.
 */
export function packagePath(assetType: string | undefined, name: string, legacy = false): string {
  if (assetType !== "song" || !name || inPackageDir(name) || name === "manifest.json") return name;
  const n = RENAMED[name] || name;
  if (legacy) {
    if (MASTER_FILES.has(n) || /^art\.[^./]+$/.test(n)) return `masters/${n}`;
    return DERIVATIVE_FILES.has(n) ? `derivatives/${n}` : `sources/${n}`;
  }
  if (n === "song.json") return n;
  if (/^master\.[^./]+$/.test(n)) return `sources/master/${n}`;
  if (DERIVATIVE_FILES.has(n) && n !== "timing.json") return `output/composition/${n}`;
  return `sources/${n}`;
}

/** The full prefix-relative key a file gets inside `packageDir`; a name that is already a catalog key is kept. */
export function packageKey(packageDir: string | null, assetType: string | undefined, name: string): string {
  const placed = packagePath(assetType, name, isLegacyDir(packageDir));
  if (!packageDir || assetType !== "song" || isPackageKey(placed)) return placed;
  return `${packageDir}/${placed}`;
}

/** The live file that a flat name refers to — same basename after placement, so a re-upload replaces in place. */
export function findByBase<T extends { name?: string }>(files: T[], assetType: string | undefined, name: string): T | undefined {
  const base = baseName(packagePath(assetType, name));
  return files.find((f) => baseName(completedPackageName(f.name)) === base);
}
